version: 2.1

jobs:
  test-3.9:
    docker:
      - image: cimg/python:3.10.13
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: pip3 install tox tox-pyenv
      - run:
          command: tox
          name: Run package tests across all python variants
      - store_test_results:
          path: reports

  test-3.10:
    docker:
      - image: cimg/python:3.10.5
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: pip3 install tox tox-pyenv
      - run:
          command: tox
          name: Run package tests across all python variants
      - store_test_results:
          path: reports

  test-3.11:
    docker:
      - image: cimg/python:3.11
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: pip3 install tox tox-pyenv
      - run:
          command: tox
          name: Run package tests across all python variants
      - store_test_results:
          path: reports

  build:
    docker:
      - image: cimg/python:3.11
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: pip3 install tox tox-pyenv
      - run:
          command: pip install build
          name: Install build dependency
      - run:
          command: python3 -m build
          name: Build source distribution
      - store_artifacts:
          path: ./dist

workflows:
  main:
    jobs:
      - test-3.9
      - test-3.10
      - test-3.11
      - build
          requires
            - test-3.9
            - test-3.10
            - test-3.11
