version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: pip3 install tox tox-pyenv
      - run: pyenv install --skip-existing 3.9.13
      - run: pyenv install --skip-existing 3.10.5
      - run: pyenv install --skip-existing 3.11-dev
      - run:
          name: Set local Python versions
          command: pyenv local 3.9.13 3.10.5 3.11-dev
      - run:
          command: tox
          name: Run package tests across all python variants
      - store_test_results:
          path: reports
      - run:
          command: pip install build
          name: Install build dependency
      - run:
          command: python3 -m build
          name: Build source distribution
      - store_artifacts:
          path: ./dist

workflows:
  main:
    jobs:
      - build-and-test
