version: 2.1

jobs:
  test:
    parameters:
      python_version:
        description: "The Python version to use for running the tests"
        type: string
    docker:
      - image: cimg/python:<< parameters.python_version >>
      - image: circleci/mongo:latest-ram
    steps:
      - checkout
      - run:
          name: Save Python Version
          command: |
            python --version > pythonversion
      - restore_cache:
          keys:
            - v1-python-{{ checksum "pythonversion" }}-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python -m venv ~/venv
            . ~/venv/bin/activate
            pip install .
            pip install -r dev-requirements.txt
      - save_cache:
          paths:
            - ~/venv
          key: v1-python-{{ checksum "pythonversion" }}-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Run Tests
          command: |
            . ~/venv/bin/activate
            pytest --cov=mogo --cov-report=term --cov-report=xml:reports/coverage-results.xml --junit-xml reports/test-results.xml tests/
      - run:
          name: Check Types
          command: |
            . ~/venv/bin/activate
            mypy -p mogo -p tests --strict --junit-xml reports/type-checking-results.xml
      - run:
          name: Run Linter
          command: |
            . ~/venv/bin/activate
            flake8
      - store_test_results:
          path: reports
          prefix: python-<< parameters.python_version >>

  build:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run:
          command: pip install build
          name: Install build dependency
      - run:
          command: python3 -m build
          name: Build source distribution
      - store_artifacts:
          path: ./dist

workflows:
  main:
    jobs:
      - test:
          name: test-3.7
          python_version: "3.7"
      - test:
          name: test-3.8
          python_version: "3.8"
      - test:
          name: test-3.9
          python_version: "3.9"
      - build
